#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post1'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 1)
__CHEETAH_genTime__ = 1762934485.2838178
__CHEETAH_genTimestamp__ = 'Wed Nov 12 05:01:25 2025'
__CHEETAH_src__ = '../m/StateState_c.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Nov 12 04:06:31 2025'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class StateState_c(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(StateState_c, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        id = VFFSL(SL,"index",True)
        write('''#include "''')
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"name",True),"capitalize",False)() # '${state.states[id].name.capitalize()}' on line 2, col 12
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].name.capitalize()}')) # from line 2, col 12.
        write('''State.h"
#include "''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 3, col 12
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 3, col 12.
        write('''StateInternal.h"

/* Possible transition to the following state: */
#include "''')
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True),"capitalize",False)() # '${state.states[id].to.capitalize()}' on line 6, col 12
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to.capitalize()}')) # from line 6, col 12.
        write('''State.h"

#include "message.h" // DEBUG

static void ''')
        _v = VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True) # '${state.states[id].to}' on line 10, col 13
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to}')) # from line 10, col 13.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 10, col 35
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 10, col 35.
        write(''' (''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 10, col 63
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 10, col 63.
        write('''StatePtr state)
{
    message("** ''')
        _v = VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True) # '${state.states[id].to}' on line 12, col 17
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to}')) # from line 12, col 17.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 12, col 39
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 12, col 39.
        write(''' **");

    ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # '${state.transitionTo.name}' on line 14, col 5
        if _v is not None: write(_filter(_v, rawExpr='${state.transitionTo.name}')) # from line 14, col 5.
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True),"capitalize",False)() # '${state.states[id].to.capitalize()}' on line 14, col 31
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to.capitalize()}')) # from line 14, col 31.
        write(''' (state);
}

void ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # '${state.transitionTo.name}' on line 17, col 6
        if _v is not None: write(_filter(_v, rawExpr='${state.transitionTo.name}')) # from line 17, col 6.
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"name",True),"capitalize",False)() # '${state.states[id].name.capitalize()}' on line 17, col 32
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].name.capitalize()}')) # from line 17, col 32.
        write(''' (''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 17, col 71
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 17, col 71.
        write('''StatePtr state)
{
    message("** ''')
        _v = VFFSL(SL,"state.transitionTo.name",True) # '${state.transitionTo.name}' on line 19, col 17
        if _v is not None: write(_filter(_v, rawExpr='${state.transitionTo.name}')) # from line 19, col 17.
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"name",True),"capitalize",False)() # '${state.states[id].name.capitalize()}' on line 19, col 43
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].name.capitalize()}')) # from line 19, col 43.
        write(''' **");

    /* Initialize with the default implementation before
       specifying the events to be handled in the started
       state. */

    ''')
        _v = VFFSL(SL,"state.defaultImplementation.name",True) # '${state.defaultImplementation.name}' on line 25, col 5
        if _v is not None: write(_filter(_v, rawExpr='${state.defaultImplementation.name}')) # from line 25, col 5.
        write(''' (state);
    state->''')
        _v = VFN(VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True),"lower",False)() # '${state.states[id].to.lower()}' on line 26, col 12
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to.lower()}')) # from line 26, col 12.
        write(''' = ''')
        _v = VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True) # '${state.states[id].to}' on line 26, col 45
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to}')) # from line 26, col 45.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 26, col 67
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 26, col 67.
        write(''';
    /*state->func = ''')
        _v = VFN(VFN(VFFSL(SL,"state",True),"states",True)[id],"to",True) # '${state.states[id].to}' on line 27, col 21
        if _v is not None: write(_filter(_v, rawExpr='${state.states[id].to}')) # from line 27, col 21.
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 27, col 43
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 27, col 43.
        write(''';*/
}

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_StateState_c = 'respond'

## END CLASS DEFINITION

if not hasattr(StateState_c, '_initCheetahAttributes'):
    templateAPIClass = getattr(StateState_c,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(StateState_c)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=StateState_c()).run()


