#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Cheetah.compat import unicode

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '3.2.6.post1'
__CHEETAH_versionTuple__ = (3, 2, 6, 'post', 1)
__CHEETAH_genTime__ = 1762935542.463354
__CHEETAH_genTimestamp__ = 'Wed Nov 12 05:19:02 2025'
__CHEETAH_src__ = '../m/State_h.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Nov 12 04:06:31 2025'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class State_h(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(State_h, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''#ifndef ''')
        _v = VFN(VFFSL(SL,"state.name",True),"upper",False)() # '${state.name.upper()}' on line 1, col 10
        if _v is not None: write(_filter(_v, rawExpr='${state.name.upper()}')) # from line 1, col 10.
        write('''_STATE_H
#define ''')
        _v = VFN(VFFSL(SL,"state.name",True),"upper",False)() # '${state.name.upper()}' on line 2, col 10
        if _v is not None: write(_filter(_v, rawExpr='${state.name.upper()}')) # from line 2, col 10.
        write('''_STATE_H

/* An incomplete type for the state representation itself. */
typedef struct ''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 5, col 16
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 5, col 16.
        write('''State* ''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 5, col 49
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 5, col 49.
        write('''StatePtr;

void ''')
        _v = VFFSL(SL,"state.defaultImplementation.name",True) # '${state.defaultImplementation.name}' on line 7, col 6
        if _v is not None: write(_filter(_v, rawExpr='${state.defaultImplementation.name}')) # from line 7, col 6.
        write(''' (''')
        _v = VFN(VFFSL(SL,"state.name",True),"capitalize",False)() # '${state.name.capitalize()}' on line 7, col 43
        if _v is not None: write(_filter(_v, rawExpr='${state.name.capitalize()}')) # from line 7, col 43.
        write('''StatePtr state);

#endif
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_State_h = 'respond'

## END CLASS DEFINITION

if not hasattr(State_h, '_initCheetahAttributes'):
    templateAPIClass = getattr(State_h,
                               '_CHEETAH_templateClass',
                               Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(State_h)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit https://cheetahtemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=State_h()).run()


